//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivePassword.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LivePassword.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add file.
        /// </summary>
        public static string addfile {
            get {
                return ResourceManager.GetString("addfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string addimage {
            get {
                return ResourceManager.GetString("addimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a new item.
        /// </summary>
        public static string addnewitem {
            get {
                return ResourceManager.GetString("addnewitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your files safe. Add the ability to archive any type of file in live password. Upgrade to Professional at a cost of 1,49USD.
        /// </summary>
        public static string buyfullversion {
            get {
                return ResourceManager.GetString("buyfullversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string cDelete {
            get {
                return ResourceManager.GetString("cDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change password.
        /// </summary>
        public static string changepassword {
            get {
                return ResourceManager.GetString("changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear all.
        /// </summary>
        public static string clearall {
            get {
                return ResourceManager.GetString("clearall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string cOpen {
            get {
                return ResourceManager.GetString("cOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string copied {
            get {
                return ResourceManager.GetString("copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        public static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string creditcard {
            get {
                return ResourceManager.GetString("creditcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string cShare {
            get {
                return ResourceManager.GetString("cShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        public static string cvv {
            get {
                return ResourceManager.GetString("cvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV copied succesfully.
        /// </summary>
        public static string cvvcopied {
            get {
                return ResourceManager.GetString("cvvcopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string dateofbirth {
            get {
                return ResourceManager.GetString("dateofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted!.
        /// </summary>
        public static string deleted {
            get {
                return ResourceManager.GetString("deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this credential?.
        /// </summary>
        public static string deletestring {
            get {
                return ResourceManager.GetString("deletestring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive your passwords, your notes, your files in Live Password.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver License.
        /// </summary>
        public static string driverlicense {
            get {
                return ResourceManager.GetString("driverlicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;555&apos;.
        /// </summary>
        public static string excvvcreditcard {
            get {
                return ResourceManager.GetString("excvvcreditcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;D&apos;.
        /// </summary>
        public static string exdriverclass {
            get {
                return ResourceManager.GetString("exdriverclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;08/22&apos;.
        /// </summary>
        public static string exdriverexpires {
            get {
                return ResourceManager.GetString("exdriverexpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;08/12&apos;.
        /// </summary>
        public static string exdriverissued {
            get {
                return ResourceManager.GetString("exdriverissued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;Westley Rotolo&apos;.
        /// </summary>
        public static string exdrivername {
            get {
                return ResourceManager.GetString("exdrivername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;FJEK34S&apos;.
        /// </summary>
        public static string exdrivernumber {
            get {
                return ResourceManager.GetString("exdrivernumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;12/21&apos;.
        /// </summary>
        public static string exexpirationcreditcard {
            get {
                return ResourceManager.GetString("exexpirationcreditcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;02/92&apos;.
        /// </summary>
        public static string exidentitydateofbirth {
            get {
                return ResourceManager.GetString("exidentitydateofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;08/22&apos;.
        /// </summary>
        public static string exidentityexpires {
            get {
                return ResourceManager.GetString("exidentityexpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;08/12&apos;.
        /// </summary>
        public static string exidentityissued {
            get {
                return ResourceManager.GetString("exidentityissued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;Westley Rotolo&apos;.
        /// </summary>
        public static string exidentityname {
            get {
                return ResourceManager.GetString("exidentityname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;TFJE3D&apos;.
        /// </summary>
        public static string exidentitynumber {
            get {
                return ResourceManager.GetString("exidentitynumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;New York&apos;.
        /// </summary>
        public static string exidentityplaceofbirth {
            get {
                return ResourceManager.GetString("exidentityplaceofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;user@example.com&apos;.
        /// </summary>
        public static string exmailmail {
            get {
                return ResourceManager.GetString("exmailmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;5593384738573847&apos;.
        /// </summary>
        public static string exnumbercreditcard {
            get {
                return ResourceManager.GetString("exnumbercreditcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;02/92&apos;.
        /// </summary>
        public static string expassportdateofbirth {
            get {
                return ResourceManager.GetString("expassportdateofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;08/22&apos;.
        /// </summary>
        public static string expassportexpires {
            get {
                return ResourceManager.GetString("expassportexpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;08/12&apos;.
        /// </summary>
        public static string expassportissued {
            get {
                return ResourceManager.GetString("expassportissued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;Westley Rotolo&apos;.
        /// </summary>
        public static string expassportname {
            get {
                return ResourceManager.GetString("expassportname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;Italian&apos;.
        /// </summary>
        public static string expassportnationality {
            get {
                return ResourceManager.GetString("expassportnationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;MJKSI3S&apos;.
        /// </summary>
        public static string expassportnumber {
            get {
                return ResourceManager.GetString("expassportnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;New York&apos;.
        /// </summary>
        public static string expassportplaceofbirth {
            get {
                return ResourceManager.GetString("expassportplaceofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;password&apos;.
        /// </summary>
        public static string expasswordlogin {
            get {
                return ResourceManager.GetString("expasswordlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;5429&apos;.
        /// </summary>
        public static string expincreditcard {
            get {
                return ResourceManager.GetString("expincreditcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        public static string expiration {
            get {
                return ResourceManager.GetString("expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration copied succesfully.
        /// </summary>
        public static string expirationcopied {
            get {
                return ResourceManager.GetString("expirationcopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        public static string expires {
            get {
                return ResourceManager.GetString("expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;password&apos;.
        /// </summary>
        public static string exrouterpassword {
            get {
                return ResourceManager.GetString("exrouterpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;Telecom-83470&apos;.
        /// </summary>
        public static string exrouterssid {
            get {
                return ResourceManager.GetString("exrouterssid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;Home&apos;s Router&apos;.
        /// </summary>
        public static string exroutertitle {
            get {
                return ResourceManager.GetString("exroutertitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;https://amazon.com&apos;.
        /// </summary>
        public static string exsitesite {
            get {
                return ResourceManager.GetString("exsitesite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;RUSJ839DSI3JFCA0&apos;.
        /// </summary>
        public static string exssncode {
            get {
                return ResourceManager.GetString("exssncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;08/22&apos;.
        /// </summary>
        public static string exssnexpires {
            get {
                return ResourceManager.GetString("exssnexpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;Westley Rotolo&apos;.
        /// </summary>
        public static string exssnname {
            get {
                return ResourceManager.GetString("exssnname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;text of my note&apos;.
        /// </summary>
        public static string extextnote {
            get {
                return ResourceManager.GetString("extextnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;Master Card&apos;.
        /// </summary>
        public static string extitlecreditcard {
            get {
                return ResourceManager.GetString("extitlecreditcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;my private files&apos;.
        /// </summary>
        public static string extitlefile {
            get {
                return ResourceManager.GetString("extitlefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;my private photo&apos;.
        /// </summary>
        public static string extitleimage {
            get {
                return ResourceManager.GetString("extitleimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;my notebook&apos;.
        /// </summary>
        public static string extitlelogin {
            get {
                return ResourceManager.GetString("extitlelogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;Outlook&apos;.
        /// </summary>
        public static string extitlemail {
            get {
                return ResourceManager.GetString("extitlemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;my private note&apos;.
        /// </summary>
        public static string extitlenote {
            get {
                return ResourceManager.GetString("extitlenote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;Amazon&apos;.
        /// </summary>
        public static string extitleweb {
            get {
                return ResourceManager.GetString("extitleweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;Wes&apos;.
        /// </summary>
        public static string exuserlogin {
            get {
                return ResourceManager.GetString("exuserlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;user@example.com&apos;.
        /// </summary>
        public static string exusersite {
            get {
                return ResourceManager.GetString("exusersite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex: &apos;https://www.outlook.com&apos;.
        /// </summary>
        public static string exwebsitemail {
            get {
                return ResourceManager.GetString("exwebsitemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must not be empty.
        /// </summary>
        public static string fieldnotempty {
            get {
                return ResourceManager.GetString("fieldnotempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file deleted succesfully.
        /// </summary>
        public static string filedeleted {
            get {
                return ResourceManager.GetString("filedeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved in OneDrive root&apos;s.
        /// </summary>
        public static string FileSalvato {
            get {
                return ResourceManager.GetString("FileSalvato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to website.
        /// </summary>
        public static string goweb {
            get {
                return ResourceManager.GetString("goweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide.
        /// </summary>
        public static string hide {
            get {
                return ResourceManager.GetString("hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        public static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Card.
        /// </summary>
        public static string identitycard {
            get {
                return ResourceManager.GetString("identitycard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image deleted succesfully.
        /// </summary>
        public static string imagedelete {
            get {
                return ResourceManager.GetString("imagedelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string images {
            get {
                return ResourceManager.GetString("images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image saved in media library.
        /// </summary>
        public static string imagesaved {
            get {
                return ResourceManager.GetString("imagesaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import files.
        /// </summary>
        public static string importfile {
            get {
                return ResourceManager.GetString("importfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import picture.
        /// </summary>
        public static string importpicture {
            get {
                return ResourceManager.GetString("importpicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert new password.
        /// </summary>
        public static string insertnewpassword {
            get {
                return ResourceManager.GetString("insertnewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert password.
        /// </summary>
        public static string insertpassword {
            get {
                return ResourceManager.GetString("insertpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued.
        /// </summary>
        public static string issued {
            get {
                return ResourceManager.GetString("issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string keyword {
            get {
                return ResourceManager.GetString("keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Password Professional.
        /// </summary>
        public static string LivePasswordPro {
            get {
                return ResourceManager.GetString("LivePasswordPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail copied succesfully.
        /// </summary>
        public static string mailcopied {
            get {
                return ResourceManager.GetString("mailcopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage keywords.
        /// </summary>
        public static string managekey {
            get {
                return ResourceManager.GetString("managekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Password.
        /// </summary>
        public static string MasterPassword {
            get {
                return ResourceManager.GetString("MasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please modify your title.
        /// </summary>
        public static string modfytitle {
            get {
                return ResourceManager.GetString("modfytitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please modify your expiration.
        /// </summary>
        public static string modifyexpiration {
            get {
                return ResourceManager.GetString("modifyexpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please modify your mail.
        /// </summary>
        public static string modifymail {
            get {
                return ResourceManager.GetString("modifymail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please modify your number.
        /// </summary>
        public static string modifynumer {
            get {
                return ResourceManager.GetString("modifynumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please modify your password.
        /// </summary>
        public static string modifypassword {
            get {
                return ResourceManager.GetString("modifypassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please modify your text.
        /// </summary>
        public static string modifytext {
            get {
                return ResourceManager.GetString("modifytext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please modify your user.
        /// </summary>
        public static string modifyuser {
            get {
                return ResourceManager.GetString("modifyuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please modify your CVV.
        /// </summary>
        public static string modifyvv {
            get {
                return ResourceManager.GetString("modifyvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please modify your web site.
        /// </summary>
        public static string modifyweb {
            get {
                return ResourceManager.GetString("modifyweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string nationality {
            get {
                return ResourceManager.GetString("nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new keyword.
        /// </summary>
        public static string newkeywords {
            get {
                return ResourceManager.GetString("newkeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data will be saved in a text file is not encrypted in your account OneDrive.
        /// </summary>
        public static string nocryptonedrive {
            get {
                return ResourceManager.GetString("nocryptonedrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no data to display.
        /// </summary>
        public static string nodata {
            get {
                return ResourceManager.GetString("nodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no keywords.
        /// </summary>
        public static string nokeywords {
            get {
                return ResourceManager.GetString("nokeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number copied succesfully.
        /// </summary>
        public static string numbercopied {
            get {
                return ResourceManager.GetString("numbercopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string office {
            get {
                return ResourceManager.GetString("office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        public static string passport {
            get {
                return ResourceManager.GetString("passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password copied succesfully.
        /// </summary>
        public static string passwordcopied {
            get {
                return ResourceManager.GetString("passwordcopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password incorrrect..
        /// </summary>
        public static string passwordincorrect {
            get {
                return ResourceManager.GetString("passwordincorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password do not match.
        /// </summary>
        public static string passwordnotmatch {
            get {
                return ResourceManager.GetString("passwordnotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Audio.
        /// </summary>
        public static string pAudio {
            get {
                return ResourceManager.GetString("pAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Credit Card.
        /// </summary>
        public static string pCreditCard {
            get {
                return ResourceManager.GetString("pCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Driver License.
        /// </summary>
        public static string pDriverLicense {
            get {
                return ResourceManager.GetString("pDriverLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Files.
        /// </summary>
        public static string pFiles {
            get {
                return ResourceManager.GetString("pFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  images.
        /// </summary>
        public static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Identity Card.
        /// </summary>
        public static string pIdentityCard {
            get {
                return ResourceManager.GetString("pIdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Images.
        /// </summary>
        public static string pImages {
            get {
                return ResourceManager.GetString("pImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        public static string pin {
            get {
                return ResourceManager.GetString("pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN copied succesfully.
        /// </summary>
        public static string pincopied {
            get {
                return ResourceManager.GetString("pincopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Birth.
        /// </summary>
        public static string placeofbirth {
            get {
                return ResourceManager.GetString("placeofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Login.
        /// </summary>
        public static string pLogin {
            get {
                return ResourceManager.GetString("pLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Mail.
        /// </summary>
        public static string pmail {
            get {
                return ResourceManager.GetString("pmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Note.
        /// </summary>
        public static string pnote {
            get {
                return ResourceManager.GetString("pnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Documenti.
        /// </summary>
        public static string pOffice {
            get {
                return ResourceManager.GetString("pOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Passport.
        /// </summary>
        public static string pPassport {
            get {
                return ResourceManager.GetString("pPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Router.
        /// </summary>
        public static string pRouter {
            get {
                return ResourceManager.GetString("pRouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Social Security Number.
        /// </summary>
        public static string pSocialSecurityNumber {
            get {
                return ResourceManager.GetString("pSocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase full version.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Video.
        /// </summary>
        public static string pVideo {
            get {
                return ResourceManager.GetString("pVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Web Site.
        /// </summary>
        public static string pWebSite {
            get {
                return ResourceManager.GetString("pWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat password.
        /// </summary>
        public static string repeatpassword {
            get {
                return ResourceManager.GetString("repeatpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat new password.
        /// </summary>
        public static string repeatpasswowrd {
            get {
                return ResourceManager.GetString("repeatpasswowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Router.
        /// </summary>
        public static string router {
            get {
                return ResourceManager.GetString("router", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        public static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share credit card information..
        /// </summary>
        public static string sharecreditcard {
            get {
                return ResourceManager.GetString("sharecreditcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share login information..
        /// </summary>
        public static string sharelogin {
            get {
                return ResourceManager.GetString("sharelogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share mail information..
        /// </summary>
        public static string sharemail {
            get {
                return ResourceManager.GetString("sharemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share note information..
        /// </summary>
        public static string sharenote {
            get {
                return ResourceManager.GetString("sharenote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string shares {
            get {
                return ResourceManager.GetString("shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share site web information..
        /// </summary>
        public static string sharesite {
            get {
                return ResourceManager.GetString("sharesite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site copied succesfully.
        /// </summary>
        public static string sitecopied {
            get {
                return ResourceManager.GetString("sitecopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Security Number.
        /// </summary>
        public static string socialsecuritynumber {
            get {
                return ResourceManager.GetString("socialsecuritynumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSID.
        /// </summary>
        public static string SSID {
            get {
                return ResourceManager.GetString("SSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap word to delete.
        /// </summary>
        public static string tapword {
            get {
                return ResourceManager.GetString("tapword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text copied succesfully.
        /// </summary>
        public static string textcopied {
            get {
                return ResourceManager.GetString("textcopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title copied succesfully.
        /// </summary>
        public static string titlecopied {
            get {
                return ResourceManager.GetString("titlecopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Version.
        /// </summary>
        public static string Trial {
            get {
                return ResourceManager.GetString("Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload on OneDrive.
        /// </summary>
        public static string uploadOneDrive {
            get {
                return ResourceManager.GetString("uploadOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User copied succesfully.
        /// </summary>
        public static string usercopied {
            get {
                return ResourceManager.GetString("usercopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSite.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
    }
}
